* octave
https://octave.org/octave.pdf

** install
sudo dnf install octave
[2019-08-09 fre] on fedora, i get octave 4.4.1, while v5.1 is current.

the repo provided octave works, but i couldnt get some plot window
features mentioned in book to work, so i wanted to try v5.1

https://flathub.org/apps/details/org.octave.Octave

sudo flatpak install flathub org.octave.Octave

flatpak run org.octave.Octave

flatpak install was super slow, until i did sudo flatpak install.

** demo plot
surf(peaks)

you get a plot window, i was able to toggle rotate and pan controllers
and play with the view, both in v4 and v5.

** trying out octave


octave 

octave:1> A=[2,0;0,2]
A =

   2   0
   0   2

octave:2> b=[2;1]
b =

   2
   1

octave:3> x=A\b
x =

   1.00000
   0.50000



octave:4> exp(i*pi)
ans = -1.0000e+00 + 1.2246e-16i

B=rand(3,2)
B =

   0.64306   0.83821
   0.48778   0.14730
   0.81420   0.23428

A=[1,1,2;3,5,8;13,21,34]

** plotting
     x = -10:0.1:10;
octave:12>      plot (x, sin (x));
octave:13> WARNING: Application calling GLX 1.3 function "glXCreatePbuffer" when GLX 1.3 is not supported!  This is an application bug!

octave:14>      xlabel ("x");
octave:15>      ylabel ("sin (x)");
octave:16>      title ("Simple 2-D Plot");
octave:17>      plot (x, cos (x));

     plot (x, sin (x), x, cos(x));

3d plot:
     tx = ty = linspace (-8, 8, 41)';
     [xx, yy] = meshgrid (tx, ty);
     r = sqrt (xx .^ 2 + yy .^ 2) + eps;
     tz = sin (r) ./ r;
     mesh (tx, ty, tz);
     xlabel ("tx");
     ylabel ("ty");
     zlabel ("tz");
     title ("3-D Sombrero plot");

plotting a function using fplot:
fh=@(x) sin(pi*x) ./ (pi*x);
octave:3> fplot(fh,[-5,5]);
octave:4> WARNING: Application calling GLX 1.3 function "glXCreatePbuffer" when GLX 1.3 is not supported!  This is an application bug!

octave:4> fh(1)
ans =    3.8982e-17
octave:5> 

** installing pkgs
dnf install octave-symbolic
pkg list
Package Name  | Version | Installation directory
--------------+---------+-----------------------
    symbolic  |   2.8.0 | /usr/share/octave/packages/symbolic-2.8.0

sudo dnf install 'octave-*'

pkg list
Package Name    | Version | Installation directory
----------------+---------+-----------------------
communications  |   1.2.1 | /usr/share/octave/packages/communications-1.2.1
       control  |   3.2.0 | /usr/share/octave/packages/control-3.2.0
         dicom  |   0.2.1 | /usr/share/octave/packages/dicom-0.2.1
       doctest  |   0.6.1 | /usr/share/octave/packages/doctest-0.6.1
       general  |   2.1.0 | /usr/share/octave/packages/general-2.1.0
 geographiclib  |    1.43 | /usr/share/octave/packages/geographiclib-1.49
           gsl  |   2.0.0 | /usr/share/octave/packages/gsl-2.0.0
         image  |   2.8.1 | /usr/share/octave/packages/image-2.8.1
      interval  |   3.2.0 | /usr/share/octave/packages/interval-3.2.0
            io  |  2.4.12 | /usr/share/octave/packages/io-2.4.12
       jsonlab  |     1.8 | /usr/share/octave/packages/jsonlab-1.8
        mathgl  | 2.4.2.1 | /usr/share/octave/packages/mathgl-2.4.2.1
         metch  |   0.5.0 | /usr/share/octave/packages/metch-0.5.0
 miscellaneous  |   1.2.1 | /usr/share/octave/packages/miscellaneous-1.2.1
       ncarray  |   1.0.4 | /usr/share/octave/packages/ncarray-1.0.4
        netcdf  |  1.0.12 | /usr/share/octave/packages/netcdf-1.0.12
         nlopt  |   2.5.0 | /usr/share/octave/packages/NLopt-2.5.0
          nnet  |  0.1.13 | /usr/share/octave/packages/nnet-0.1.13
        odepkg  |   0.9.1 | /usr/share/octave/packages/odepkg-0.9.1
         optim  |   1.6.0 | /usr/share/octave/packages/optim-1.6.0
      parallel  |   3.1.3 | /usr/share/octave/packages/parallel-3.1.3
    quaternion  |   2.4.0 | /usr/share/octave/packages/quaternion-2.4.0
        signal  |   1.4.1 | /usr/share/octave/packages/signal-1.4.1
       specfun  |   1.1.0 | /usr/share/octave/packages/specfun-1.1.0
    statistics  |   1.4.0 | /usr/share/octave/packages/statistics-1.4.0
        struct  |  1.0.15 | /usr/share/octave/packages/struct-1.0.15
      symbolic  |   2.8.0 | /usr/share/octave/packages/symbolic-2.8.0
