* different ways of running clojure in a shellscript

a lot of stuff we do is scripting using bash, perl, cron in openshift,
makefiles, and so on. its good to be able to mix tools.

sometimes, though, you want the power of a real language
... you want, LISP!

still you want to have the entire mix of languages available to you. a
single curl call shouldnt be hundreds of lines of java, python, or
whatever, it should be a single curl call.

so, you want lisp, but you also want shell scripting.

contained here are a couple of examples how to do it.

the current favorite is bash-shebang-underscore-hack.clj, because you
use plain clojure and bash, no other dependencies.

but the others are cool too, and i will expand this...

TODO

theres a bunch of other ways with their own tradeoffs

** cider
bash-shebang-underscore-hack.clj includes deps in the script, which is
convenient, but the clj tools and cider wants them in a deps.edn file,
so atm 2 copies of deps.edn are needed.

** references



https://github.com/jafingerhut/dotfiles/blob/master/templates/clj-template-README.md


    http://inlein.org/

    
    https://joker-lang.org/

    https://github.com/borkdude/babashka

    https://github.com/dundalek/closh



    https://planck-repl.org/

    
